apiVersion: skaffold/v4beta3
manifests:
  rawYaml:
    - ./infra/k8s/*
kind: Config

deploy:
  kubectl: {}

build:
  local:
    push: false
  artifacts:
    - image: raulargottc/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.ts
  